### ISSUE TITLE
Compilation error with ESPHome 2026.3.0: multiple definition of `__wrap_esp_panic_handler'

### ISSUE THREAD

**Issue by drothenberger** [konnected-io/konnected-esphome#110]
Neither the 2026.2.0 release nor master compiles with the newly released ESPHome 2026.3.0.

```
Linking .pioenvs/konnected-gdo-v2-q/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld: .pioenvs/konnected-gdo-v2-q/src/esphome/components/secplus_gdo/secplus_gdo.cpp.o: in function `__wrap_esp_panic_handler':
/data/build/konnected-gdo-v2-q/src/esphome/components/secplus_gdo/secplus_gdo.cpp:183: multiple definition of `__wrap_esp_panic_handler'; .pioenvs/konnected-gdo-v2-q/src/esphome/components/esp32/crash_handler.cpp.o:/data/build/konnected-gdo-v2-q/src/esphome/components/esp32/crash_handler.cpp:272: first defined here
collect2: error: ld returned 1 exit status
*** [.pioenvs/konnected-gdo-v2-q/firmware.elf] Error 1
```

**Comment by arazilsongweaver** [comment]
The new ESPHome crash reporting system is likely causing this failure: https://github.com/esphome/esphome/pull/14709

**Comment by heythisisnate** [comment]
Fixed in b16b385.

**Root cause:** ESPHome 2026.3.0 added a crash handler (esphome/esphome#14709) that defines its own `__wrap_esp_panic_handler` using the same `--wrap=esp_panic_handler` linker mechanism we use for GDO UART TX pin safety. This caused a "multiple definition" linker error.

**Fix:** We use a preprocessor macro (`-D__wrap_esp_panic_handler=__esphome_wrap_esp_panic_handler`) added via the component's `__init__.py` to rename ESPHome's definition at compile time. Our `secplus_gdo.cpp` then `#undef`s the macro so it can define the real `__wrap_esp_panic_handler`, which:

1. Disables the GDO UART TX pin (our safety behavior — preserved)
2. Chains to ESPHome's renamed handler (crash backtrace capture — preserved)
3. Which then calls the original IDF panic handler

Both behaviors are fully preserved. The `-Wl,--wrap=esp_panic_handler` build flag was also removed from YAML configs since ESPHome now adds it automatically.
