### ISSUE TITLE
GDO Blaq: Compilation error with ESPHome 2026.7.0

### ISSUE THREAD

**Issue by drothenberger** [konnected-io/konnected-esphome#120]
I cannot get 2026.6.0 to compile with ESPHome 2026.7.0. I tried both with and without `toolchain: platformio`. Here is the error with `toolchain: platformio`: 
```
In file included from src/esphome/components/secplus_gdo/secplus_gdo.h:26,
                 from src/esphome/components/secplus_gdo/secplus_gdo.cpp:18:
src/esphome/components/secplus_gdo/light/gdo_light.h:27:7: error: cannot derive from 'final' base 'esphome::binary::BinaryLightOutput' in derived type 'esphome::secplus_gdo::GDOLight'
   27 | class GDOLight : public binary::BinaryLightOutput, public Component {
      |       ^~~~~~~~
*** [.pioenvs/konnected-gdo-v2-q/src/esphome/components/secplus_gdo/secplus_gdo.cpp.o] Error 1
```
